export enum PropertyType {
  APARTMENT = 'APARTMENT',
  MINI_APARTMENT = 'MINI_APARTMENT',
  HOUSE = 'HOUSE',
  LAND = 'LAND',
  COMMERCIAL = 'COMMERCIAL',
  OFFICE = 'OFFICE',
  INDUSTRIAL = 'INDUSTRIAL',
}
